version: "3.1"
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:24.8-alpine
    hostname: clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - airflow
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - CLICKHOUSE_PASSWORD=12345678