version: 2

sources:
  - name: data_source
    schema: default
    tables:
      - name: entity_has_master_materials
      - name: master_materials
      - name: stocks
      - name: master_activities
      - name: batches
      - name: entity_master_material_activities
      - name: entity_entity_tags
      - name: provinces
      - name: regencies
      - name: entities
      - name: entity_tags
      - name: master_material_has_activities